st.title("Perguntados")
st.text_input("Cadê o Josir?")
st.text_input("Pêra ou maçã?")
st.text_input("Flamengo é o maior do mundo: sim ou com certeza?")
st.text_input("Qual seu sabor favorito de pizza?")
st.button("Continuar")
